#!/bin/sh

# this script runs when a display manager logs you in or when startx is run from a TTY
# put things in here that you want to auto start when logging in to your GUI.


# setup monitors the way I like them.
2-mon.sh &

# set wallpaper using xwallpaper (you can replace this with xwal to get a random wallpaper)
xwp &

# increases speed of the cursor when moving around.
xset r rate 300 50 &

# start sxhkd
sxhkd &
